version: '3'
services:
  vue-client:
     image: client
     command: serve -s dist
     ports:
       - "80:5000"

  node-server:
    image: api
    restart: always
    ports:
      - "4200:4200"
    # links:
    #   - mongo
  socket-io-server:
    image: socket
    restart: always
    ports:
      - "3000:3000"