version: '3'
services:
  vue-client:
    image: ./client
    command: npm run serve
    ports:
      - "8080:8080"

  node-server:
    image: api
    restart: allways
    ports:
      - "9000:9000"
    links:
      - mongo
  socket-io-server:
    image: socket
    restart: allways
    ports:
      - "3000:3000"
      
  mongo:
    image: mongo
    ports:
      - "27017:27017" 